### PR TITLE
Add syntax highlighting for LanguageClient-neovim

### PR DESCRIPTION
**Pull request by Logarithmus**

### CODE REVIEW

**Comment by lifepillar** [comment]
There is some inconsistency between the template and the various color schemes. Could you please check again?

**Comment by Logarithmus** [comment]
> There is some inconsistency between the template and the various color schemes. Could you please check again?

How did you spot the incosistency? Honestly, I just copied LSP's entries and modified them a bit. I don't understand the purpose of color templates.

**Comment by lifepillar** [comment]
The color schemes are generated automatically from the templates using [Colortemplate](https://github.com/lifepillar/vim-colortemplate). You've done more work than necessary :-)

Anyway, if you confirm that the colors in `_plugins` are correct, I can rebuild all the color schemes accordingly.

**Comment by Logarithmus** [comment]
@lifepillar I've figured out colortemplates and updated my PR accordingly.

**Comment by lifepillar** [comment]
Thanks for contributing!

**Pull request merged**
