### PR TITLE
Add Airline Support

### LINKED ISSUE #17: Set Airline Theme
Greetings,

In the pictures in README.md there seems to be some status line plugin. I'd like to know which one and how can I set the theme to gruvbox8. 

Thanks in advance,

MyriadAsura

### PR DESCRIPTION
**Pull request by binarypie**
Coming from the original gruvbox theme I missed airline support.
This pull request would close #17 if accepted.

To Enable:
```
let g:airline_theme = 'gruvbox8'
```

### CODE REVIEW

**Comment by shivamashtikar** [comment]
Can we get this PR merged

**Comment by lifepillar** [comment]
“This commit does not belong to any branch on this repository”.  @binarypie Can you please rebase this on the current master?

**Comment by binarypie** [comment]
@lifepillar you should be all set now. Let me know. I'm sorry I missed this for so long.

**Comment by lifepillar** [comment]
Sorry for taking so long to merge this. Thanks for your contribution!

**Pull request merged**
